site_name: Nutritional Deficiency Detection
nav:
  - Home: docs/README.md
  - Getting Started: docs/getting-started.md
  - Data Mapper: docs/data-manager.md
  - Data Generator: docs/custom-data-generator.md
  - Usage:
      - Mapper: docs/examples/usage-mapper.md
      - Generator: docs/examples/usage-generator.md
theme:
  name: material
